// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMPCUBtH8OkVFK_4gtadVqIqdF_rZU9M',
    appId: '1:511856634071:web:58ab9ac51bec28872ea892',
    messagingSenderId: '511856634071',
    projectId: 'cafeteria-instituto',
    authDomain: 'cafeteria-instituto.firebaseapp.com',
    databaseURL: 'https://cafeteria-instituto-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cafeteria-instituto.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGMPCUBtH8OkVFK_4gtadVqIqdF_rZU9M',
    appId: '1:511856634071:web:27f4cfad9e3ade712ea892',
    messagingSenderId: '511856634071',
    projectId: 'cafeteria-instituto',
    authDomain: 'cafeteria-instituto.firebaseapp.com',
    databaseURL: 'https://cafeteria-instituto-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cafeteria-instituto.appspot.com',
  );
}
